# Generated by Django 2.0.13 on 2019-11-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
