# Generated by Django 2.0.13 on 2019-11-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_headshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='headshot',
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
