# Generated by Django 2.0.13 on 2019-11-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191130_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ppt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
