# Generated by Django 2.0.13 on 2019-11-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_ppt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='filelink',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
