# Generated by Django 2.0.13 on 2019-11-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_filelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='filelink',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='ppt',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
