# Generated by Django 2.0.13 on 2019-11-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191130_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ppt',
        ),
    ]
